### PR TITLE
Refine cross staff beams

### LINKED ISSUE #1847: Auto stem.dir behavior in mixed beam cases
Here is an example of mixed beams with various types of stem directions.  The text describes the stem directions of the highlighted note in the measure. 

Screen Shot 2020-11-23 at 6 19 09 AM

In particular for this issue, note the third measure where the stem direction is automatically assigned by verovio.   Verovio should assign an up-stem direction in this case, since the beam is above the note.  Verovio is giving it a down-stem assignment for some reason, and this results in the stem being on the wrong side of the notehead when it is attached to the beam.

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-11-23T06:46:41" version="3.1.0-dev-0b664f2">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="31" token="!!!RDF**kern: @ = marked note" xml:id="L32">
     <frameInfo>
      <startTime float="9.5" ratfrac="1/2" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>@ = marked note</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000860333826">
    <score xml:id="score-0000002014721097">
     <scoreDef xml:id="scoredef-0000001714114210">
      <staffGrp xml:id="staffgrp-0000001237981080">
       <staffDef xml:id="staffdef-0000001690090931" n="1" lines="5">
        <clef xml:id="clef-0000000778692251" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000147817808" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L4F1-L7F1">
          <note xml:id="note-L4F1" dur="8" oct="4" pname="c" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L5F1" type="marked" dur="8" oct="4" pname="d" color="red" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L6F1" dur="8" oct="5" pname="g" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L7F1" dur="8" oct="5" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dir xml:id="dir-L3F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="rend-0000001108725207" fontstyle="normal">stem up</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L8">
       <staff xml:id="staff-L8F1N1" n="1">
        <layer xml:id="layer-L8F1N1" n="1">
         <beam xml:id="beam-L10F1-L13F1">
          <note xml:id="note-L10F1" dur="8" oct="4" pname="c" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L11F1" type="marked" dur="8" oct="4" pname="d" color="red" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L12F1" dur="8" oct="5" pname="g" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L13F1" dur="8" oct="5" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dir xml:id="dir-L9F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="rend-0000001256096647" fontstyle="normal">stem down</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L14">
       <staff xml:id="staff-L14F1N1" n="1">
        <layer xml:id="layer-L14F1N1" n="1">
         <beam xml:id="beam-L16F1-L19F1">
          <note xml:id="note-L16F1" dur="8" oct="4" pname="c" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L17F1" type="marked" dur="8" oct="4" pname="d" color="red" accid.ges="n" />
          <note xml:id="note-L18F1" dur="8" oct="5" pname="g" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L19F1" dur="8" oct="5" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dir xml:id="dir-L15F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="rend-0000001247729019" fontstyle="normal">auto stem</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L20">
       <staff xml:id="staff-L20F1N1" n="1">
        <layer xml:id="layer-L20F1N1" n="1">
         <beam xml:id="beam-L22F1-L25F1">
          <note xml:id="note-L22F1" dur="8" oct="4" pname="c" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L23F1" dur="8" oct="4" pname="d" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L24F1" dur="8" oct="5" pname="g" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L25F1" type="marked" dur="8" oct="5" pname="f" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dir xml:id="dir-L21F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="rend-0000001210483963" fontstyle="normal">auto stem</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L26">
       <staff xml:id="staff-L26F1N1" n="1">
        <layer xml:id="layer-L26F1N1" n="1">
         <beam xml:id="beam-L27F1-L29F1">
          <note xml:id="note-L27F1" dur="8" oct="4" pname="c" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L28F1" dur="8" oct="4" pname="d" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L29F1" dur="8" oct="5" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

---------------

Other discussion unrelated to the issue:

The other measures are given just to examine the behavior of the new mix-beam feature.  Measure 1 has the second note explicitly stem-up as needed for the mixed beam.  Measure 2 has the second not stem down, contrary to the mixed beaming.  This behavior is expected since the beam is not possible to mix if the second note is stem-down.

The fourth measure is an interesting behavior: when the last note is given an automatic stem direction, the beam becomes horizontal.   The placement of the text above the staff in the last measure is unusual:  It is placed higher above the staff than in the previous measure, probably because it is incorrectly assuming that the last note is up-stem (its stem direction is automatic, but the automatic assignment is down-stem, which is probably not available to the text placement algorithm).

Also outside the scope of this issue: Priority also seems to be given to the down-stem notes at the end of the beam when assigning the beam location.  Ideally the horizontal beam in the last measure should be centered more equally between the notes.  When only considering the two endnotes of the beam, the best angle would be down, but when the notes in the middle are added either a horizontal or beam slanted up would probably be best.   Such cases may be too complicated for an algorithm to always get it right, so probably assigning explicit stem lengths to the first/last notes in the mixed beam group will often need to be done.

### LINKED ISSUE #1939: Horizontal beam case
In the following example, all beams should be horizontal:

Screen Shot 2021-01-09 at 10 24 23 PM

but measures 1, 2, 4, 5, 6, 8 and 11, 12, 15, 16 the beams are slanted.

The red color indicates a note that changes between each beamed group.  The blue notes are the notes closest to the beam (used to decide on horizontalness of beam).

<details>
<summary>
Click to see MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-09T22:46:27" version="3.1.0-dev-3c64e38-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="101" token="!!!RDF**kern: @ = marked note" xml:id="L102">
     <frameInfo>
      <startTime float="20" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>@ = marked note</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="102" token="!!!RDF**kern: + = marked note, color=dodgerblue" xml:id="L103">
     <frameInfo>
      <startTime float="20" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>+ = marked note, color=dodgerblue</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000552853167">
    <score xml:id="score-0000001241739569">
     <scoreDef xml:id="scoredef-0000000447449745">
      <staffGrp xml:id="staffgrp-0000000439961906">
       <staffDef xml:id="staffdef-0000000679768727" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000261649459" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L4F1-L9F1">
          <note xml:id="note-L4F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L5F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L6F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L7F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L8F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L9F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L10" n="2">
       <staff xml:id="staff-L10F1N1" n="1">
        <layer xml:id="layer-L10F1N1" n="1">
         <beam xml:id="beam-L11F1-L16F1">
          <note xml:id="note-L11F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L12F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L13F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L14F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L15F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L16F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L17" n="3">
       <staff xml:id="staff-L17F1N1" n="1">
        <layer xml:id="layer-L17F1N1" n="1">
         <beam xml:id="beam-L18F1-L23F1">
          <note xml:id="note-L18F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L19F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L20F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L21F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L22F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L23F1" type="marked" dur="16" oct="4" pname="d" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L24" n="4">
       <staff xml:id="staff-L24F1N1" n="1">
        <layer xml:id="layer-L24F1N1" n="1">
         <beam xml:id="beam-L25F1-L30F1">
          <note xml:id="note-L25F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L26F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L27F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L28F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L29F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L30F1" type="marked" dur="16" oct="4" pname="e" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L31" n="5">
       <staff xml:id="staff-L31F1N1" n="1">
        <layer xml:id="layer-L31F1N1" n="1">
         <beam xml:id="beam-L32F1-L35F1">
          <note xml:id="note-L32F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L33F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L34F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L35F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L36" n="6">
       <staff xml:id="staff-L36F1N1" n="1">
        <layer xml:id="layer-L36F1N1" n="1">
         <beam xml:id="beam-L37F1-L40F1">
          <note xml:id="note-L37F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L38F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L39F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L40F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L41" n="7">
       <staff xml:id="staff-L41F1N1" n="1">
        <layer xml:id="layer-L41F1N1" n="1">
         <beam xml:id="beam-L42F1-L45F1">
          <note xml:id="note-L42F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L43F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L44F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L45F1" type="marked" dur="16" oct="4" pname="d" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L46" right="dbl" n="8">
       <staff xml:id="staff-L46F1N1" n="1">
        <layer xml:id="layer-L46F1N1" n="1">
         <beam xml:id="beam-L47F1-L50F1">
          <note xml:id="note-L47F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L48F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L49F1" type="marked" dur="16" oct="3" pname="a" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L50F1" type="marked" dur="16" oct="4" pname="e" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L51" n="9">
       <staff xml:id="staff-L51F1N1" n="1">
        <layer xml:id="layer-L51F1N1" n="1">
         <clef xml:id="clef-L52F1" shape="G" line="2" />
         <beam xml:id="beam-L53F1-L58F1">
          <note xml:id="note-L53F1" type="marked" dur="16" oct="3" pname="g" color="red" accid.ges="n" />
          <note xml:id="note-L54F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L55F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L56F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L57F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L58F1" dur="16" oct="3" pname="b" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L59" n="10">
       <staff xml:id="staff-L59F1N1" n="1">
        <layer xml:id="layer-L59F1N1" n="1">
         <beam xml:id="beam-L60F1-L65F1">
          <note xml:id="note-L60F1" type="marked" dur="16" oct="3" pname="a" color="red" accid.ges="n" />
          <note xml:id="note-L61F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L62F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L63F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L64F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L65F1" dur="16" oct="4" pname="c" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L66" n="11">
       <staff xml:id="staff-L66F1N1" n="1">
        <layer xml:id="layer-L66F1N1" n="1">
         <beam xml:id="beam-L67F1-L72F1">
          <note xml:id="note-L67F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
          <note xml:id="note-L68F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L69F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L70F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L71F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L72F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L73" n="12">
       <staff xml:id="staff-L73F1N1" n="1">
        <layer xml:id="layer-L73F1N1" n="1">
         <beam xml:id="beam-L74F1-L79F1">
          <note xml:id="note-L74F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
          <note xml:id="note-L75F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L76F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L77F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L78F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L79F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L80" n="13">
       <staff xml:id="staff-L80F1N1" n="1">
        <layer xml:id="layer-L80F1N1" n="1">
         <beam xml:id="beam-L81F1-L84F1">
          <note xml:id="note-L81F1" type="marked" dur="16" oct="3" pname="g" color="red" accid.ges="n" />
          <note xml:id="note-L82F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L83F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L84F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L85" n="14">
       <staff xml:id="staff-L85F1N1" n="1">
        <layer xml:id="layer-L85F1N1" n="1">
         <beam xml:id="beam-L86F1-L89F1">
          <note xml:id="note-L86F1" type="marked" dur="16" oct="3" pname="a" color="red" accid.ges="n" />
          <note xml:id="note-L87F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L88F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L89F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L90" n="15">
       <staff xml:id="staff-L90F1N1" n="1">
        <layer xml:id="layer-L90F1N1" n="1">
         <beam xml:id="beam-L91F1-L94F1">
          <note xml:id="note-L91F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
          <note xml:id="note-L92F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L93F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L94F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L95" n="16">
       <staff xml:id="staff-L95F1N1" n="1">
        <layer xml:id="layer-L95F1N1" n="1">
         <beam xml:id="beam-L96F1-L99F1">
          <note xml:id="note-L96F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
          <note xml:id="note-L97F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L98F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L99F1" type="marked" dur="16" oct="4" pname="d" color="dodgerblue" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

In the following example, all of the beams are horizontal as expected:

Screen Shot 2021-01-09 at 10 38 00 PM

What is happening is that a check for the closest internal note to the beam is being made and the horizontal rule is being triggered since it is closer than either outer notes.  In the first example, the highest internal note does not exceed a note at the beam's edge; however, if the highest internal note is equal to one of the external notes, the horizontal rule should also be triggered.

<details>
<summary>
Click to see MEI data for the above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-09T22:42:32" version="3.1.0-dev-3c64e38-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="101" token="!!!RDF**kern: @ = marked note" xml:id="L102">
     <frameInfo>
      <startTime float="20" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>@ = marked note</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="102" token="!!!RDF**kern: + = marked note, color=dodgerblue" xml:id="L103">
     <frameInfo>
      <startTime float="20" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>+ = marked note, color=dodgerblue</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001949548001">
    <score xml:id="score-0000000001863190">
     <scoreDef xml:id="scoredef-0000000447449745">
      <staffGrp xml:id="staffgrp-0000001711061676">
       <staffDef xml:id="staffdef-0000002025853842" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001312653865" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L4F1-L9F1">
          <note xml:id="note-L4F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L5F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L6F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L7F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L8F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L9F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L10" n="2">
       <staff xml:id="staff-L10F1N1" n="1">
        <layer xml:id="layer-L10F1N1" n="1">
         <beam xml:id="beam-L11F1-L16F1">
          <note xml:id="note-L11F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L12F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L13F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L14F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L15F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L16F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L17" n="3">
       <staff xml:id="staff-L17F1N1" n="1">
        <layer xml:id="layer-L17F1N1" n="1">
         <beam xml:id="beam-L18F1-L23F1">
          <note xml:id="note-L18F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L19F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L20F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L21F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L22F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L23F1" type="marked" dur="16" oct="4" pname="d" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L24" n="4">
       <staff xml:id="staff-L24F1N1" n="1">
        <layer xml:id="layer-L24F1N1" n="1">
         <beam xml:id="beam-L25F1-L30F1">
          <note xml:id="note-L25F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L26F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L27F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L28F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L29F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L30F1" type="marked" dur="16" oct="4" pname="e" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L31" n="5">
       <staff xml:id="staff-L31F1N1" n="1">
        <layer xml:id="layer-L31F1N1" n="1">
         <beam xml:id="beam-L32F1-L35F1">
          <note xml:id="note-L32F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L33F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L34F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L35F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L36" n="6">
       <staff xml:id="staff-L36F1N1" n="1">
        <layer xml:id="layer-L36F1N1" n="1">
         <beam xml:id="beam-L37F1-L40F1">
          <note xml:id="note-L37F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L38F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L39F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L40F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L41" n="7">
       <staff xml:id="staff-L41F1N1" n="1">
        <layer xml:id="layer-L41F1N1" n="1">
         <beam xml:id="beam-L42F1-L45F1">
          <note xml:id="note-L42F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L43F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L44F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L45F1" type="marked" dur="16" oct="4" pname="d" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L46" right="dbl" n="8">
       <staff xml:id="staff-L46F1N1" n="1">
        <layer xml:id="layer-L46F1N1" n="1">
         <beam xml:id="beam-L47F1-L50F1">
          <note xml:id="note-L47F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L48F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L49F1" type="marked" dur="16" oct="3" pname="g" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L50F1" type="marked" dur="16" oct="4" pname="e" color="red" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L51" n="9">
       <staff xml:id="staff-L51F1N1" n="1">
        <layer xml:id="layer-L51F1N1" n="1">
         <clef xml:id="clef-L52F1" shape="G" line="2" />
         <beam xml:id="beam-L53F1-L58F1">
          <note xml:id="note-L53F1" type="marked" dur="16" oct="3" pname="g" color="red" accid.ges="n" />
          <note xml:id="note-L54F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L55F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L56F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L57F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L58F1" dur="16" oct="3" pname="b" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L59" n="10">
       <staff xml:id="staff-L59F1N1" n="1">
        <layer xml:id="layer-L59F1N1" n="1">
         <beam xml:id="beam-L60F1-L65F1">
          <note xml:id="note-L60F1" type="marked" dur="16" oct="3" pname="a" color="red" accid.ges="n" />
          <note xml:id="note-L61F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L62F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L63F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L64F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L65F1" dur="16" oct="4" pname="c" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L66" n="11">
       <staff xml:id="staff-L66F1N1" n="1">
        <layer xml:id="layer-L66F1N1" n="1">
         <beam xml:id="beam-L67F1-L72F1">
          <note xml:id="note-L67F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
          <note xml:id="note-L68F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L69F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L70F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L71F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L72F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L73" n="12">
       <staff xml:id="staff-L73F1N1" n="1">
        <layer xml:id="layer-L73F1N1" n="1">
         <beam xml:id="beam-L74F1-L79F1">
          <note xml:id="note-L74F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
          <note xml:id="note-L75F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L76F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L77F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L78F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L79F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L80" n="13">
       <staff xml:id="staff-L80F1N1" n="1">
        <layer xml:id="layer-L80F1N1" n="1">
         <beam xml:id="beam-L81F1-L84F1">
          <note xml:id="note-L81F1" type="marked" dur="16" oct="3" pname="g" color="red" accid.ges="n" />
          <note xml:id="note-L82F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L83F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L84F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L85" n="14">
       <staff xml:id="staff-L85F1N1" n="1">
        <layer xml:id="layer-L85F1N1" n="1">
         <beam xml:id="beam-L86F1-L89F1">
          <note xml:id="note-L86F1" type="marked" dur="16" oct="3" pname="a" color="red" accid.ges="n" />
          <note xml:id="note-L87F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L88F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L89F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L90" n="15">
       <staff xml:id="staff-L90F1N1" n="1">
        <layer xml:id="layer-L90F1N1" n="1">
         <beam xml:id="beam-L91F1-L94F1">
          <note xml:id="note-L91F1" type="marked" dur="16" oct="3" pname="b" color="red" accid.ges="n" />
          <note xml:id="note-L92F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L93F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L94F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L95" n="16">
       <staff xml:id="staff-L95F1N1" n="1">
        <layer xml:id="layer-L95F1N1" n="1">
         <beam xml:id="beam-L96F1-L99F1">
          <note xml:id="note-L96F1" type="marked" dur="16" oct="4" pname="c" color="red" accid.ges="n" />
          <note xml:id="note-L97F1" type="marked" dur="16" oct="4" pname="e" color="dodgerblue" accid.ges="n" />
          <note xml:id="note-L98F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L99F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

### LINKED ISSUE #1957: Mixed-stem beam enhancement for horizontal cases
In these examples (measures 1 and 3):

Screen Shot 2021-01-14 at 6 16 52 PM

<details>
<summary>
Click to view MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-14T18:15:58" version="3.1.0-dev-0361cac-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000470629727">
    <score xml:id="score-0000001898726912">
     <scoreDef xml:id="scoredef-0000000083058839" midi.bpm="120">
      <staffGrp xml:id="staffgrp-0000000499771795" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-0000001622392097" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
        <keySig xml:id="keysig-L3F2" pname="a" mode="major" sig="0" />
        <meterSig xml:id="metersig-L5F2" count="2" unit="4" />
       </staffDef>
       <staffDef xml:id="staffdef-0000000237236015" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <keySig xml:id="keysig-L3F1" pname="a" mode="major" sig="0" />
        <meterSig xml:id="metersig-L5F1" count="2" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000002064744994" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <space xml:id="space-L8F2" dur="4" />
         <space xml:id="space-L10F2" dur="2" />
         <space xml:id="space-L14F2" dur="1" />
        </layer>
       </staff>
       <staff xml:id="staff-0000001766969499" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L8F1-L9F1">
          <note xml:id="note-L8F1" type="placed" dur="8" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L9F1" type="placed" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L10F1-L13F1">
          <note xml:id="note-L10F1" type="placed" dur="8" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L11F1" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L12F1" dur="8" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L13F1" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L14F1-L17F1">
          <note xml:id="note-L14F1" type="placed" dur="8" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L15F1" type="placed" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
          <chord xml:id="chord-L16F1" type="placed" dur="8" stem.dir="up">
           <note xml:id="note-L16F1S1" oct="3" pname="a" accid.ges="n" />
           <note xml:id="note-L16F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L17F1" type="placed" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L18F1-L21F1">
          <chord xml:id="chord-L18F1" type="placed" dur="8" stem.dir="up">
           <note xml:id="note-L18F1S1" oct="3" pname="a" accid.ges="n" />
           <note xml:id="note-L18F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L19F1" type="placed" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
          <chord xml:id="chord-L20F1" type="placed" dur="8" stem.dir="up">
           <note xml:id="note-L20F1S1" oct="3" pname="a" accid.ges="n" />
           <note xml:id="note-L20F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L21F1" type="placed" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L22">
       <staff xml:id="staff-L22F2N1" n="1">
        <layer xml:id="layer-L22F2N1" n="1">
         <space xml:id="space-L23F2" dur="1" />
        </layer>
       </staff>
       <staff xml:id="staff-L22F1N1" n="2">
        <layer xml:id="layer-L22F1N1" n="1">
         <beam xml:id="beam-L23F1-L26F1">
          <note xml:id="note-L23F1" dur="8" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L24F1" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
          <chord xml:id="chord-L25F1" dur="8">
           <note xml:id="note-L25F1S1" oct="3" pname="a" accid.ges="n" />
           <note xml:id="note-L25F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L26F1" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L27F1-L30F1" type="placed">
          <note xml:id="note-L27F1" dur="8" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L28F1" dur="8" staff="1" oct="4" pname="e" stem.dir="up" accid.ges="n" />
          <chord xml:id="chord-L29F1" dur="8" stem.dir="up">
           <note xml:id="note-L29F1S1" oct="3" pname="a" accid.ges="n" />
           <note xml:id="note-L29F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L30F1" dur="8" staff="1" oct="4" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L31">
       <staff xml:id="staff-L31F2N1" n="1">
        <layer xml:id="layer-L31F2N1" n="1">
         <space xml:id="space-L32F2" dots="1" dur="2" />
        </layer>
       </staff>
       <staff xml:id="staff-L31F1N1" n="2">
        <layer xml:id="layer-L31F1N1" n="1">
         <beam xml:id="beam-L32F1-L33F1">
          <note xml:id="note-L32F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L33F1" type="placed" dur="8" oct="4" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L34F1-L37F1">
          <note xml:id="note-L34F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L35F1" type="placed" dur="8" oct="4" pname="c" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L36F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L37F1" type="placed" dur="8" oct="4" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

The mixed-stem beams should be horizontal.  It would be useful to adjust the beam angle algorithm for these cases to trigger a horizontal beam.

The refined algorithm is illustrated with measure 2: Place a hypothetical beam both above an below the mixed beam notes.  If either of these hypothetical placements triggers a horizontal beam, then the mixed-stem beam would be assigned a horizontal beam.

----------------------------------------------

Here is a real-world example:

Screen Shot 2021-01-14 at 6 39 23 PM

which currently looks hilarious in verovio:

Screen Shot 2021-01-14 at 6 38 19 PM

https://verovio.humdrum.org/?file=beethoven/sonatas/sonata02-1.krn&k=ey#m135

<details>
<summary>
Click to view MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title>Piano Sonata no. 2 in A major</title>
   </titleStmt>
   <pubStmt>
    <respStmt>
     <persName xml:id="persname-L84" analog="humdrum:EED" role="editor">Craig Stuart Sapp</persName>
    </respStmt>
   </pubStmt>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-14T18:43:16" version="3.1.0-dev-0361cac-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
   <projectDesc>
    <p>Encoded by: Craig Stuart Sapp</p>
   </projectDesc>
  </encodingDesc>
  <workList>
   <work>
    <title xml:id="title-L3" analog="humdrum:OTL" type="main">Piano Sonata no. 2 in A major</title>
    <composer analog="humdrum:COM" xml:id="person-L1">Beethoven, Ludwig van</composer>
    <creation>
     <date analog="humdrum:ODT">1794///-1795///</date>
    </creation>
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="0" token="!!!COM: Beethoven, Ludwig van" xml:id="L1">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>COM</referenceKey>
      <referenceValue>Beethoven, Ludwig van</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="1" token="!!!CDT: 1770///-1827///" xml:id="L2">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>CDT</referenceKey>
      <referenceValue>1770///-1827///</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="2" token="!!!OTL: Piano Sonata no. 2 in A major" xml:id="L3">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>OTL</referenceKey>
      <referenceValue>Piano Sonata no. 2 in A major</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="3" token="!!!ODT: 1794///-1795///" xml:id="L4">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>ODT</referenceKey>
      <referenceValue>1794///-1795///</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="4" token="!!!ODE: Joseph Haydn" xml:id="L5">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>ODE</referenceKey>
      <referenceValue>Joseph Haydn</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="5" token="!!!OMD: Allegro vivace" xml:id="L6">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>OMD</referenceKey>
      <referenceValue>Allegro vivace</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="6" token="!!!OPS: 2" xml:id="L7">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>OPS</referenceKey>
      <referenceValue>2</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="7" token="!!!ONM: 2" xml:id="L8">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>ONM</referenceKey>
      <referenceValue>2</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="8" token="!!!OMV: 1" xml:id="L9">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>OMV</referenceKey>
      <referenceValue>1</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="9" token="!!!AGN: Sonata" xml:id="L10">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>AGN</referenceKey>
      <referenceValue>Sonata</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="78" token="!!!RDF**kern: > = above" xml:id="L79">
     <frameInfo>
      <startTime float="12" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>&gt; = above</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="79" token="!!!RDF**kern: &lt; = below" xml:id="L80">
     <frameInfo>
      <startTime float="12" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>&lt; = below</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="80" token="!!!ENC: Craig Stuart Sapp" xml:id="L81">
     <frameInfo>
      <startTime float="12" />
      <frameType>reference</frameType>
      <referenceKey>ENC</referenceKey>
      <referenceValue>Craig Stuart Sapp</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="81" token="!!!END: 2004/06/30/" xml:id="L82">
     <frameInfo>
      <startTime float="12" />
      <frameType>reference</frameType>
      <referenceKey>END</referenceKey>
      <referenceValue>2004/06/30/</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="82" token="!!!END: 2019/07/02/" xml:id="L83">
     <frameInfo>
      <startTime float="12" />
      <frameType>reference</frameType>
      <referenceKey>END</referenceKey>
      <referenceValue>2019/07/02/</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="83" token="!!!EED: Craig Stuart Sapp" xml:id="L84">
     <frameInfo>
      <startTime float="12" />
      <frameType>reference</frameType>
      <referenceKey>EED</referenceKey>
      <referenceValue>Craig Stuart Sapp</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001327438354">
    <score xml:id="score-0000000962113394">
     <scoreDef xml:id="scoredef-0000001248033213" midi.bpm="120">
      <pgHead xml:id="pghead-0000001400353444">
       <rend xml:id="rend-0000001196443802" halign="center" valign="middle">
        <rend xml:id="rend-0000000356757987" fontsize="large">Piano Sonata no. 2 in A major</rend>
        <lb xml:id="lb-0000001043468829" /> 
<lb xml:id="lb-0000000222294926" /> </rend>
       <rend xml:id="rend-0000001496986085" halign="right" valign="bottom" fontsize="small">Ludwig van Beethoven</rend>
       <rend xml:id="rend-0000000012951110" halign="right" valign="bottom" fontsize="small">1770–1827</rend>
      </pgHead>
      <staffGrp xml:id="staffgrp-0000000290516087" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-0000000778198089" n="1" lines="5">
        <clef xml:id="clef-L13F3" shape="G" line="2" />
        <keySig xml:id="keysig-L14F3" pname="a" mode="major" sig="0" />
        <meterSig xml:id="metersig-L16F3" count="2" unit="4" />
       </staffDef>
       <staffDef xml:id="staffdef-0000001634052790" n="2" lines="5">
        <clef xml:id="clef-L13F1" shape="F" line="4" />
        <keySig xml:id="keysig-L14F1" pname="a" mode="major" sig="0" />
        <meterSig xml:id="metersig-L16F1" count="2" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L11F1">
      <measure xml:id="measure-L1" n="136">
       <staff xml:id="staff-0000000408660324" n="1">
        <layer xml:id="layer-L11F2N1" n="1">
         <space xml:id="space-L19F3" dots="1" dur="4" />
         <note xml:id="note-L25F3" type="placed" dur="8" oct="6" pname="e" stem.dir="up" accid="f">
          <artic xml:id="artic-L25F3" artic="stacciss" place="above" />
         </note>
        </layer>
       </staff>
       <staff xml:id="staff-0000001069776626" n="2">
        <layer xml:id="layer-L11F1N1" n="1">
         <beam xml:id="beam-L19F1-L22F1">
          <chord xml:id="chord-L19F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L19F1S1" oct="3" pname="a" accid="f" />
           <note xml:id="note-L19F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L20F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid="f" />
          <chord xml:id="chord-L21F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L21F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L21F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L22F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
         <beam xml:id="beam-L23F1-L26F1">
          <chord xml:id="chord-L23F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L23F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L23F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L24F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
          <chord xml:id="chord-L25F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L25F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L25F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L26F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
        </layer>
        <layer xml:id="layer-L13F2N2" n="2">
         <note xml:id="note-L19F2" dur="4" oct="1" pname="a" accid="f">
          <artic xml:id="artic-L19F2" artic="stacciss" />
         </note>
         <space xml:id="space-L23F2" dur="4" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L28" n="137">
       <staff xml:id="staff-L28F2N1" n="1">
        <layer xml:id="layer-L28F2N1" n="1">
         <note xml:id="note-L29F2" type="placed" dur="4" oct="6" pname="c" stem.dir="up" accid.ges="n">
          <artic xml:id="artic-L29F2" artic="stacciss" place="above" />
         </note>
         <note xml:id="note-L33F2" type="placed" dur="4" oct="5" pname="a" stem.dir="up" accid="f">
          <artic xml:id="artic-L33F2" artic="stacciss" place="above" />
         </note>
        </layer>
       </staff>
       <staff xml:id="staff-L28F1N1" n="2">
        <layer xml:id="layer-L28F1N1" n="1">
         <beam xml:id="beam-L29F1-L32F1">
          <chord xml:id="chord-L29F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L29F1S1" oct="3" pname="a" accid="f" />
           <note xml:id="note-L29F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L30F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid="f" />
          <chord xml:id="chord-L31F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L31F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L31F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L32F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
         <beam xml:id="beam-L33F1-L36F1">
          <chord xml:id="chord-L33F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L33F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L33F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L34F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
          <chord xml:id="chord-L35F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L35F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L35F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L36F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L37" n="138">
       <staff xml:id="staff-L37F2N1" n="1">
        <layer xml:id="layer-L37F2N1" n="1">
         <note xml:id="note-L38F2" type="placed" dur="4" oct="5" pname="e" stem.dir="up" accid="f">
          <artic xml:id="artic-L38F2" artic="stacciss" place="above" />
         </note>
         <note xml:id="note-L42F2" type="placed" dur="4" oct="5" pname="c" stem.dir="up" accid.ges="n">
          <artic xml:id="artic-L42F2" artic="stacciss" place="above" />
         </note>
        </layer>
       </staff>
       <staff xml:id="staff-L37F1N1" n="2">
        <layer xml:id="layer-L37F1N1" n="1">
         <beam xml:id="beam-L38F1-L41F1">
          <chord xml:id="chord-L38F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L38F1S1" oct="3" pname="a" accid="f" />
           <note xml:id="note-L38F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L39F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid="f" />
          <chord xml:id="chord-L40F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L40F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L40F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L41F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
         <beam xml:id="beam-L42F1-L45F1">
          <chord xml:id="chord-L42F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L42F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L42F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L43F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
          <chord xml:id="chord-L44F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L44F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L44F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L45F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L46" n="139">
       <staff xml:id="staff-L46F2N1" n="1">
        <layer xml:id="layer-L46F2N1" n="1">
         <note xml:id="note-L47F2" type="placed" dur="4" oct="4" pname="b" stem.dir="up" accid="f">
          <artic xml:id="artic-L47F2" artic="stacciss" place="above" />
         </note>
         <note xml:id="note-L51F2" type="placed" dur="4" oct="4" pname="a" stem.dir="up" accid="f">
          <artic xml:id="artic-L51F2" artic="stacciss" place="above" />
         </note>
        </layer>
       </staff>
       <staff xml:id="staff-L46F1N1" n="2">
        <layer xml:id="layer-L46F1N1" n="1">
         <beam xml:id="beam-L47F1-L50F1">
          <chord xml:id="chord-L47F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L47F1S1" oct="3" pname="a" accid="f" />
           <note xml:id="note-L47F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L48F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid="f" />
          <chord xml:id="chord-L49F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L49F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L49F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L50F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
         <beam xml:id="beam-L51F1-L54F1">
          <chord xml:id="chord-L51F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L51F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L51F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L52F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
          <chord xml:id="chord-L53F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L53F1S1" oct="3" pname="a" accid.ges="f" />
           <note xml:id="note-L53F1S2" oct="4" pname="c" accid.ges="n" />
          </chord>
          <note xml:id="note-L54F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L55" n="140">
       <staff xml:id="staff-L55F2N1" n="1">
        <layer xml:id="layer-L55F2N1" n="1">
         <note xml:id="note-L57F3" type="placed" dur="4" oct="4" pname="g" stem.dir="up" accid.ges="n">
          <artic xml:id="artic-L57F3" artic="stacciss" place="above" />
         </note>
         <rest xml:id="rest-L61F3" dur="8" />
         <space xml:id="space-L63F3" dur="8" />
        </layer>
       </staff>
       <staff xml:id="staff-L55F1N1" n="2">
        <layer xml:id="layer-L55F1N1" n="1">
         <beam xml:id="beam-L57F1-L60F1">
          <chord xml:id="chord-L57F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L57F1S1" oct="3" pname="b" accid="f" />
           <note xml:id="note-L57F1S2" oct="4" pname="d" accid="f" />
          </chord>
          <note xml:id="note-L58F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid="f" />
          <chord xml:id="chord-L59F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L59F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L59F1S2" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L59F1S3" oct="4" pname="d" accid.ges="f" />
          </chord>
          <note xml:id="note-L60F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
         <beam xml:id="beam-L61F1-L64F1">
          <chord xml:id="chord-L61F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L61F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L61F1S2" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L61F1S3" oct="4" pname="d" accid.ges="f" />
          </chord>
          <note xml:id="note-L62F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
          <chord xml:id="chord-L63F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L63F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L63F1S2" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L63F1S3" oct="4" pname="d" accid.ges="f" />
          </chord>
          <note xml:id="note-L64F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
        </layer>
        <layer xml:id="layer-L57F2N2" n="2">
         <space xml:id="space-L57F2" dots="1" dur="4" />
         <note xml:id="note-L63F2" dur="8" oct="3" pname="e" accid="f">
          <artic xml:id="artic-L63F2" artic="stacciss" />
         </note>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L65" n="141">
       <staff xml:id="staff-L65F3N1" n="1">
        <layer xml:id="layer-L65F3N1" n="1">
         <mRest xml:id="mrest-L66F3" visible="false" />
        </layer>
       </staff>
       <staff xml:id="staff-L65F1N1" n="2">
        <layer xml:id="layer-L65F1N1" n="1">
         <beam xml:id="beam-L66F1-L69F1">
          <chord xml:id="chord-L66F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L66F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L66F1S2" oct="3" pname="b" accid="f" />
           <note xml:id="note-L66F1S3" oct="4" pname="d" accid="f" />
          </chord>
          <note xml:id="note-L67F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid="f" />
          <chord xml:id="chord-L68F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L68F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L68F1S2" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L68F1S3" oct="4" pname="d" accid.ges="f" />
          </chord>
          <note xml:id="note-L69F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
         <beam xml:id="beam-L70F1-L74F1">
          <chord xml:id="chord-L70F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L70F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L70F1S2" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L70F1S3" oct="4" pname="d" accid.ges="f" />
          </chord>
          <note xml:id="note-L71F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
          <chord xml:id="chord-L72F1" type="placed" dur="16" stem.dir="up">
           <note xml:id="note-L72F1S1" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L72F1S2" oct="3" pname="b" accid.ges="f" />
           <note xml:id="note-L72F1S3" oct="4" pname="d" accid.ges="f" />
          </chord>
          <note xml:id="note-L74F1" type="placed" dur="16" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
         </beam>
        </layer>
        <layer xml:id="layer-L65F2N2" n="2">
         <note xml:id="note-L66F2" dur="4" oct="2" pname="b" accid="f">
          <artic xml:id="artic-L66F2" artic="stacciss" />
         </note>
         <rest xml:id="rest-L70F2" dur="8" ploc="g" oloc="2" />
         <beam xml:id="beam-L72F2-L75F2">
          <note xml:id="note-L72F2" dur="32" oct="2" pname="b" accid.ges="f" />
          <note xml:id="note-L73F2" dur="32" oct="2" pname="a" accid="f" />
          <note xml:id="note-L74F2" dur="32" oct="2" pname="g" accid.ges="n" />
          <note xml:id="note-L75F2" dur="32" oct="2" pname="f" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

### LINKED ISSUE #2004: Mixed beam + chord interaction
When an attempt to apply mixed beams to chords is aborted, strange stems get added to the inner notes of chords:

Screen Shot 2021-01-27 at 11 05 52 PM

These chord notes that are not in the head position think that the beam is above them rather than below, and they think they are on the head side of the chord, although they are aware that the beam they are probably trying to attach to is on the wrong side since the stems are on the side of the noteheads opposite to where they should be.

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-27T23:09:56" version="3.2.0-dev-f52d8f1-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000002136518158">
    <score xml:id="score-0000000378747661">
     <scoreDef xml:id="scoredef-0000000495797626">
      <staffGrp xml:id="staffgrp-0000000812391674">
       <staffDef xml:id="staffdef-0000001118318590" n="1" lines="5">
        <clef xml:id="clef-0000000397378791" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000000708520943" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L3F1-L7F1">
          <note xml:id="note-L3F1" type="placed" dur="8" oct="2" pname="c" stem.dir="up" accid.ges="n" />
          <chord xml:id="chord-L4F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L4F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L4F1S2" oct="4" pname="d" accid.ges="n" />
          </chord>
          <chord xml:id="chord-L5F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L5F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L5F1S2" oct="3" pname="b" accid.ges="n" />
          </chord>
          <chord xml:id="chord-L6F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L6F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L6F1S2" oct="3" pname="g" accid.ges="n" />
          </chord>
          <note xml:id="note-L7F1" type="placed" dur="8" oct="3" pname="a" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L8">
       <staff xml:id="staff-L8F1N1" n="1">
        <layer xml:id="layer-L8F1N1" n="1">
         <beam xml:id="beam-L9F1-L13F1">
          <note xml:id="note-L9F1" type="placed" dur="8" oct="2" pname="c" stem.dir="up" accid.ges="n" />
          <chord xml:id="chord-L10F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L10F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L10F1S2" oct="4" pname="d" accid.ges="n" />
          </chord>
          <chord xml:id="chord-L11F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L11F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L11F1S2" oct="3" pname="b" accid.ges="n" />
          </chord>
          <chord xml:id="chord-L12F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L12F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L12F1S2" oct="3" pname="g" accid.ges="n" />
          </chord>
          <note xml:id="note-L13F1" type="placed" dur="8" oct="3" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### LINKED ISSUE #2159: Regression on double-stemmed beams from verovio 2.6.0
Hello,
I have noticed a regression on double-stemmed beams from verovio 2.6.0, unfixed until now (3.3.0 at date writing).

The code:

~~~ xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo />
        </encodingDesc>
        <workList>
            <work>
                <title />
            </work>
        </workList>
    </meiHead>
 <music>
  <body>
   <mdiv>
    <score>
       <scoreDef xml:id="scoredef-0000000578035858">
         <staffGrp xml:id="staffgrp-0000001760475413">
            <staffGrp xml:id="P2" bar.thru="true">
               <staffDef xml:id="staffdef-0000001967435478" n="1" lines="5" ppq="8">
                  <clef xml:id="clef-0000000788455254" shape="G" line="2" />
                  <keySig xml:id="keysig-0000001618717358" mode="major" sig="3s" />
                  <meterSig xml:id="msig-0000001360290431" count="2" unit="4" />
               </staffDef>
               <staffDef xml:id="staffdef-0000001182616957" n="2" lines="5" ppq="8">
                  <clef xml:id="clef-0000001684181138" shape="F" line="4" />
                  <keySig xml:id="keysig-0000001418539404" mode="major" sig="3s" />
                  <meterSig xml:id="msig-0000000103265385" count="2" unit="4" />
               </staffDef>
               <grpSym xml:id="grpsym-0000000284264140" symbol="brace" />
            </staffGrp>
         </staffGrp>
      </scoreDef>
      <section xml:id="section-0000001953199539">
         <pb xml:id="pb-0000001947861830" />
         <measure xml:id="measure-0000000138773945" n="0">
            <mNum xml:id="mnum-0000000683188048" />
            <staff xml:id="staff-0000001556924724" n="1">
               <layer xml:id="layer-0000000290978060" n="1">
                  <beam xml:id="beam-0000000050142717">
                     <note xml:id="note-0000001726589520" dur.ppq="2" dur="16" staff="2" oct="3" pname="c" stem.dir="up" accid.ges="s" />
                     <note xml:id="note-0000000627471406" dur.ppq="2" dur="16" staff="2" oct="3" pname="b" stem.dir="up" />
                     <note xml:id="note-0000000257599593" dur.ppq="2" dur="16" staff="2" oct="4" pname="c" stem.dir="up" accid.ges="s" />
                     <note xml:id="note-0000001469791881" dur.ppq="2" dur="16" oct="4" pname="e" stem.dir="down">
                        <accid xml:id="accid-0000001693654555" accid="s" accid.ges="s" />
                     </note>
                  </beam>
               </layer>
            </staff>
            <staff xml:id="staff-0000001754114227" n="2">
               <layer xml:id="layer-0000000287765726" n="1">
                  <mSpace xml:id="mSpace-0000000785798522" />
               </layer>
            </staff>
         </measure>
      </section>
   </score>
   </mdiv>
  </body>
 </music>
</mei>
~~~

produces with verovio 2.5.0:

double-stemmed beams verovio2 5 0

Strangely, all up stems are down, but at least, it's readable...

But from verovio 2.6.0, up stems are up :

regression verovio double-stemmed beams

but the result is unreadable.

Thanks

### LINKED ISSUE #2188: Mixed-stem beam enhancements
In this example:

Screen Shot 2021-05-14 at 8 18 21 AM

The first mixed-stem beam looks OK, but the rest of them are implausible since there are zero or negative stem lengths.  In all cases the bottom note of the chord on the stem side of the beam is the same note, so there should not be any variability in the beam angles that are seen in the example (the beam angles seems influenced by the to notes in the chords). 

In the case of a mixed-stem beam on two notes/chords, a good algorithm might be to make the stem lengths equal (from the note closest to the beam) if the otherwise an auto-calculated stem length is ridiculously short.  Maybe "too short" would be defined as 4 diatonic steps.

In situ example https://verovio.humdrum.org/?file=chopin-first-editions/010-1b-Sm-010.krn#mh45

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-05-14T08:32:33" version="3.5.0-dev-271f462-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000453195288">
    <score xml:id="score-0000000616049706">
     <scoreDef xml:id="scoredef-0000000761538332">
      <staffGrp xml:id="staffgrp-0000002048490768">
       <staffDef xml:id="staffdef-0000001481420080" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <meterSig xml:id="metersig-L3F1" count="12" unit="8" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="45">
       <staff xml:id="staff-0000000908004861" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L5F1-L6F1">
          <chord xml:id="chord-L5F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L5F1S1" oct="3" pname="b" accid.ges="n" />
           <note xml:id="note-L5F1S2" oct="3" pname="g" accid.ges="n" />
           <note xml:id="note-L5F1S3" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L6F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L7F1" dur="8" />
         <rest xml:id="rest-L8F1" dur="4" />
         <chord xml:id="chord-L9F1" dur="8">
          <note xml:id="note-L9F1S1" oct="3" pname="b" accid="f" />
          <note xml:id="note-L9F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
         <beam xml:id="beam-L10F1-L11F1">
          <chord xml:id="chord-L10F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L10F1S1" oct="4" pname="d" accid.ges="n" />
           <note xml:id="note-L10F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L11F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid="f" />
         </beam>
         <rest xml:id="rest-L12F1" dur="8" />
         <rest xml:id="rest-L13F1" dur="4" />
         <chord xml:id="chord-L14F1" dur="8">
          <note xml:id="note-L14F1S1" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L14F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L15" n="46">
       <staff xml:id="staff-L15F1N1" n="1">
        <layer xml:id="layer-L15F1N1" n="1">
         <beam xml:id="beam-L16F1-L17F1">
          <chord xml:id="chord-L16F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L16F1S1" oct="4" pname="c" accid.ges="n" />
           <note xml:id="note-L16F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L17F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L18F1" dur="8" />
         <rest xml:id="rest-L19F1" dur="4" />
         <chord xml:id="chord-L20F1" dur="8">
          <note xml:id="note-L20F1S1" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L20F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
         <beam xml:id="beam-L21F1-L22F1">
          <chord xml:id="chord-L21F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L21F1S1" oct="4" pname="e" accid.ges="n" />
           <note xml:id="note-L21F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L22F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid="f" />
         </beam>
         <rest xml:id="rest-L23F1" dur="8" />
         <rest xml:id="rest-L24F1" dur="4" />
         <chord xml:id="chord-L25F1" dur="8">
          <note xml:id="note-L25F1S1" oct="4" pname="e" accid.ges="n" />
          <note xml:id="note-L25F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L26" n="47">
       <staff xml:id="staff-L26F1N1" n="1">
        <layer xml:id="layer-L26F1N1" n="1">
         <beam xml:id="beam-L27F1-L28F1">
          <chord xml:id="chord-L27F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L27F1S1" oct="4" pname="d" accid.ges="n" />
           <note xml:id="note-L27F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L28F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L29F1" dur="8" />
         <rest xml:id="rest-L30F1" dur="4" />
         <chord xml:id="chord-L31F1" dur="8">
          <note xml:id="note-L31F1S1" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L31F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
         <beam xml:id="beam-L32F1-L33F1">
          <chord xml:id="chord-L32F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L32F1S1" oct="4" pname="f" accid.ges="n" />
           <note xml:id="note-L32F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L33F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L34F1" dur="8" />
         <rest xml:id="rest-L35F1" dur="4" />
         <chord xml:id="chord-L37F1" dur="8">
          <note xml:id="note-L37F1S1" oct="4" pname="f" accid.ges="n" />
          <note xml:id="note-L37F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L38" n="48">
       <staff xml:id="staff-L38F1N1" n="1">
        <layer xml:id="layer-L38F1N1" n="1">
         <beam xml:id="beam-L39F1-L40F1">
          <chord xml:id="chord-L39F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L39F1S1" oct="4" pname="e" accid.ges="n" />
           <note xml:id="note-L39F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L40F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L41F1" dur="8" />
         <rest xml:id="rest-L42F1" dur="4" />
         <chord xml:id="chord-L43F1" dur="8">
          <note xml:id="note-L43F1S1" oct="4" pname="e" accid.ges="n" />
          <note xml:id="note-L43F1S2" oct="3" pname="e" accid.ges="n" />
         </chord>
         <beam xml:id="beam-L44F1-L45F1">
          <chord xml:id="chord-L44F1" type="placed" dur="8" stem.dir="down">
           <note xml:id="note-L44F1S1" oct="4" pname="g" accid.ges="n" />
           <note xml:id="note-L44F1S2" oct="3" pname="e" accid.ges="n" />
          </chord>
          <note xml:id="note-L45F1" type="placed" dur="8" oct="2" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L46F1" dur="8" />
         <rest xml:id="rest-L47F1" dur="4" />
         <note xml:id="note-L49F1" dur="8" oct="3" pname="e" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by Monceber**
closes #2159
closes #2188 
closes #1939 
closes #1847
closes #1957
closes #2004

This PR improves several of the cross-staff beam cases, as well as introduces some general beam improvements (horizontal beam placement from #1939).
image
image
image

For this case, since mixed beam cannot be placed within the staff without overlapping with notes/stems or falling outside of the staff, it is converted to ordinary beam.
image
cross-staff-001 before and after:
image
image
cross-staff-004:
image
image
cross-staff-007:
image
image
cross-staff-023:
image
image

### CODE REVIEW

**Comment by lpugin** [comment]
@Monceber would you be able to merge the conflict and bring this up-to-date? Sorry, it came when I was having my break in December and was not able to review it then. It looks great and I would like to move it forward.

File: src/drawinginterface.cpp [hunk 1]
```diff
@@ -287,24 +298,25 @@ bool BeamDrawingInterface::IsHorizontal()
...
-    for (i = 1; i < itemCount - 1; ++i) {
-        if (m_drawingPlace == BEAMPLACE_above) {
-            if ((items.at(i) > first) && (items.at(i) > last)) return true;
-        }
-        else {
-            if ((items.at(i) < first) && (items.at(i) < last)) return true;
-        }
-    }
+    // If drawing place is mixed and is should be drawn horizontal based on mixed rules
+    if ((m_drawingPlace == BEAMPLACE_mixed) && (IsHorizontal(items, directions))) return true;
```
Comment (lpugin) [inline src/drawinginterface.cpp:302]: (style) do `this->IsHorizontal`

File: include/vrv/layerelement.h [hunk 2]
```diff
@@ -467,6 +467,22 @@ class LayerElement : public Object,
...
+     * Template for getting above/below overflow for BeamType elements (BEAM or FTREM)
+     */
+    template <class BeamType> void GetBeamOverflow(StaffAlignment *&above, StaffAlignment *&below);
+
+    /**
+     * Template for getting above/below overflow for children of BeamType elements (BEAM or FTREM)
+     */
+    template <class BeamType>
+    void GetBeamChildOverflow(StaffAlignment *&above, StaffAlignment *&below, BeamType *parent);
+
```
Comment (lpugin) [inline include/vrv/layerelement.h:480]: I am not to fond of having beam related methods with templates in LayerElement. The BeamInterface is there for not having to do this. If you need the LayerElement in some methods, you can pass it as parameter to the BeamInterface method. I would agree that this is a bit weird, but we have that already elsewhere (e.g.: ObjectListInterface::GetList(Object *)`. The main advantage would be not to overload LayerElement and to keep the beam related code in one place.

**Review by lpugin — COMMENTED** [review]
Please check beam-064. I would expect mixed directions to be possible in such cases.

image

File: include/vrv/layerelement.h (hunk 2 above)
Comment (lpugin) [reply include/vrv/layerelement.h:480]: Never mind, we can look at that later
