### PR TITLE
Fix for the spanning hairpins touching barlines

### LINKED ISSUE #1938: Hairpin + measure + system breaks interaction
As a subcase of issue https://github.com/rism-ch/verovio/issues/959, hairpins are still touching barlines when the hairpin crosses over a system break:

Screen Shot 2021-01-09 at 9 56 03 PM

Note that it is touching barlines at two locations: at the end of the system, and the end of the measure where the hairpin ends.

When the hairpin stays within a system, it behaves correctly:

Screen Shot 2021-01-09 at 9 57 42 PM

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-09T21:57:43" version="3.1.0-dev-3c64e38-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001805807804">
    <score xml:id="score-0000000040742034">
     <scoreDef xml:id="scoredef-0000000447449745" midi.bpm="138">
      <staffGrp xml:id="staffgrp-0000000503495232" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-0000001171475355" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
        <keySig xml:id="keysig-L3F2" pname="g" mode="minor" sig="2f" />
        <meterSig xml:id="metersig-L5F2" count="6" unit="8" />
       </staffDef>
       <staffDef xml:id="staffdef-0000001258612927" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <keySig xml:id="keysig-L3F1" pname="g" mode="minor" sig="2f" />
        <meterSig xml:id="metersig-L5F1" count="6" unit="8" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <pb xml:id="pb-0000000777682269" />
      <measure xml:id="measure-L1" n="66">
       <staff xml:id="staff-0000000446314909" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <note xml:id="note-L8F2" dur="4" oct="5" pname="d" accid.ges="n" />
         <note xml:id="note-L9F2" dur="8" oct="5" pname="c" accid.ges="n">
          <artic xml:id="artic-L9F2" artic="stacc" />
         </note>
         <beam xml:id="beam-L10F2-L12F2">
          <note xml:id="note-L10F2" dur="8" oct="4" pname="b" accid.ges="f">
           <artic xml:id="artic-L10F2" artic="stacc" />
          </note>
          <note xml:id="note-L11F2" dur="8" oct="4" pname="a" accid.ges="n">
           <artic xml:id="artic-L11F2" artic="stacc" />
          </note>
          <note xml:id="note-L12F2" dur="8" oct="4" pname="g" accid.ges="n">
           <artic xml:id="artic-L12F2" artic="stacc" />
          </note>
         </beam>
        </layer>
       </staff>
       <staff xml:id="staff-0000000988460300" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L8F1" dur="4" oct="4" pname="d" accid.ges="n" />
         <note xml:id="note-L9F1" dur="8" oct="4" pname="c" accid.ges="n">
          <artic xml:id="artic-L9F1" artic="stacc" />
         </note>
         <beam xml:id="beam-L10F1-L12F1">
          <note xml:id="note-L10F1" dur="8" oct="3" pname="b" accid.ges="f">
           <artic xml:id="artic-L10F1" artic="stacc" />
          </note>
          <note xml:id="note-L11F1" dur="8" oct="3" pname="a" accid.ges="n">
           <artic xml:id="artic-L11F1" artic="stacc" />
          </note>
          <note xml:id="note-L12F1" dur="8" oct="3" pname="g" accid.ges="n">
           <artic xml:id="artic-L12F1" artic="stacc" />
          </note>
         </beam>
        </layer>
       </staff>
       <dynam xml:id="dynam-L8F3" staff="1" tstamp="1.000000" vgrp="100">f</dynam>
       <slur xml:id="slur-L8F2-L9F2" staff="1" startid="#note-L8F2" endid="#note-L9F2" />
       <slur xml:id="slur-L8F1-L9F1" staff="2" startid="#note-L8F1" endid="#note-L9F1" />
      </measure>
      <measure xml:id="measure-L13" n="67">
       <staff xml:id="staff-L13F2N1" n="1">
        <layer xml:id="layer-L13F2N1" n="1">
         <beam xml:id="beam-L14F2-L16F2">
          <note xml:id="note-L14F2" dur="8" oct="4" pname="e" accid.ges="f" />
          <note xml:id="note-L15F2" dur="8" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L16F2" dur="8" oct="4" pname="b" accid.ges="f">
           <artic xml:id="artic-L16F2" artic="stacc" />
          </note>
         </beam>
         <beam xml:id="beam-L17F2-L19F2">
          <note xml:id="note-L17F2" dur="8" oct="4" pname="a" accid.ges="n">
           <artic xml:id="artic-L17F2" artic="stacc" />
          </note>
          <note xml:id="note-L18F2" dur="8" oct="4" pname="g" accid.ges="n">
           <artic xml:id="artic-L18F2" artic="stacc" />
          </note>
          <note xml:id="note-L19F2" dur="8" oct="4" pname="f" accid="s">
           <artic xml:id="artic-L19F2" artic="stacc" />
          </note>
         </beam>
        </layer>
       </staff>
       <staff xml:id="staff-L13F1N1" n="2">
        <layer xml:id="layer-L13F1N1" n="1">
         <chord xml:id="chord-L14F1" dots="1" dur="4">
          <note xml:id="note-L14F1S1" oct="3" pname="c" accid.ges="n" />
          <note xml:id="note-L14F1S2" oct="3" pname="a" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L17F1" dots="1" dur="4">
          <note xml:id="note-L17F1S1" oct="3" pname="d" accid.ges="n" />
          <note xml:id="note-L17F1S2" oct="4" pname="c" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <slur xml:id="slur-L14F2-L15F2" staff="1" startid="#note-L14F2" endid="#note-L15F2" />
      </measure>
      <sb xml:id="sb-L21F1" type="z" />
      <measure xml:id="measure-L21" n="68">
       <staff xml:id="staff-L21F2N1" n="1">
        <layer xml:id="layer-L21F2N1" n="1">
         <note xml:id="note-L22F2" dur="4" oct="4" pname="g" accid.ges="n" />
         <note xml:id="note-L26F2" dur="8" oct="6" pname="d" accid.ges="n" />
         <beam xml:id="beam-L28F2-L32F2">
          <note xml:id="note-L28F2" dur="8" oct="6" pname="d" accid.ges="n" />
          <note xml:id="note-L30F2" dur="8" oct="6" pname="c" accid="s" />
          <note xml:id="note-L32F2" dur="8" oct="6" pname="d" accid.ges="n">
           <artic xml:id="artic-L32F2" artic="stacc" />
          </note>
         </beam>
        </layer>
       </staff>
       <staff xml:id="staff-L21F1N1" n="2">
        <layer xml:id="layer-L21F1N1" n="1">
         <beam xml:id="beam-L22F1-L27F1">
          <note xml:id="note-L22F1" dur="16" oct="3" pname="g" accid.ges="n" />
          <note xml:id="note-L23F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L24F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L25F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L26F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L27F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L28F1-L33F1">
          <note xml:id="note-L28F1" dur="16" oct="3" pname="f" accid="s" />
          <note xml:id="note-L29F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L30F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L31F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L32F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L33F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dynam xml:id="dynam-L26F3" staff="1" tstamp="3.000000" vgrp="100">p</dynam>
       <hairpin xml:id="hairpin-L28F3" staff="1" tstamp="4.000000" tstamp2="1m+7.0000" form="cres" vgrp="100" />
       <slur xml:id="slur-L28F2-L30F2" staff="1" startid="#note-L28F2" endid="#note-L30F2" />
      </measure>
      <measure xml:id="measure-L34" n="69">
       <staff xml:id="staff-L34F2N1" n="1">
        <layer xml:id="layer-L34F2N1" n="1">
         <beam xml:id="beam-L35F2-L39F2">
          <note xml:id="note-L35F2" dur="8" oct="6" pname="d" accid.ges="n" />
          <note xml:id="note-L37F2" dur="8" oct="6" pname="c" accid="s" />
          <note xml:id="note-L39F2" dur="8" oct="6" pname="d" accid.ges="n">
           <artic xml:id="artic-L39F2" artic="stacc" />
          </note>
         </beam>
         <beam xml:id="beam-L41F2-L45F2">
          <note xml:id="note-L41F2" dur="8" oct="6" pname="d" accid.ges="n" />
          <note xml:id="note-L43F2" dur="8" oct="6" pname="c" accid.ges="s" />
          <note xml:id="note-L45F2" dur="8" oct="6" pname="d" accid.ges="n">
           <artic xml:id="artic-L45F2" artic="stacc" />
          </note>
         </beam>
        </layer>
       </staff>
       <staff xml:id="staff-L34F1N1" n="2">
        <layer xml:id="layer-L34F1N1" n="1">
         <beam xml:id="beam-L35F1-L40F1">
          <note xml:id="note-L35F1" dur="16" oct="3" pname="g" accid.ges="n" />
          <note xml:id="note-L36F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L37F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L38F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L39F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L40F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L41F1-L46F1">
          <note xml:id="note-L41F1" dur="16" oct="3" pname="f" accid="s" />
          <note xml:id="note-L42F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L43F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L44F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L45F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L46F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L35F2-L37F2" staff="1" startid="#note-L35F2" endid="#note-L37F2" />
       <slur xml:id="slur-L41F2-L43F2" staff="1" startid="#note-L41F2" endid="#note-L43F2" />
      </measure>
      <measure xml:id="measure-L47" n="70">
       <staff xml:id="staff-L47F2N1" n="1">
        <layer xml:id="layer-L47F2N1" n="1">
         <beam xml:id="beam-L48F2-L52F2">
          <note xml:id="note-L48F2" dur="8" oct="6" pname="d" accid.ges="n" />
          <note xml:id="note-L50F2" dur="8" oct="6" pname="c">
           <accid xml:id="accid-L50F2" accid="n" func="caution" />
          </note>
          <note xml:id="note-L52F2" dur="8" oct="5" pname="b" accid.ges="f">
           <artic xml:id="artic-L52F2" artic="stacc" />
          </note>
         </beam>
         <note xml:id="note-L54F2" dur="8" oct="6" pname="c" grace="unacc" accid.ges="n" />
         <beam xml:id="beam-L55F2-L59F2">
          <note xml:id="note-L55F2" dur="8" oct="5" pname="b" accid.ges="f" />
          <note xml:id="note-L57F2" dur="8" oct="5" pname="a" accid.ges="n" />
          <note xml:id="note-L59F2" dur="8" oct="5" pname="g" accid.ges="n">
           <artic xml:id="artic-L59F2" artic="stacc" />
          </note>
         </beam>
        </layer>
       </staff>
       <staff xml:id="staff-L47F1N1" n="2">
        <layer xml:id="layer-L47F1N1" n="1">
         <beam xml:id="beam-L48F1-L53F1">
          <note xml:id="note-L48F1" dur="16" oct="3" pname="g" accid.ges="n" />
          <note xml:id="note-L49F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L50F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L51F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L52F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L53F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L55F1-L60F1">
          <note xml:id="note-L55F1" dur="16" oct="3" pname="g" accid.ges="n" />
          <note xml:id="note-L56F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L57F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L58F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L59F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L60F1" dur="16" oct="4" pname="d" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dynam xml:id="dynam-L48F3" staff="1" tstamp="1.000000" vgrp="100">f</dynam>
       <slur xml:id="slur-L48F2-L50F2" staff="1" startid="#note-L48F2" endid="#note-L50F2" />
       <slur xml:id="slur-L54F2-L55F2" staff="1" startid="#note-L54F2" endid="#note-L55F2" />
       <slur xml:id="slur-L55F2-L57F2" staff="1" startid="#note-L55F2" endid="#note-L57F2" />
      </measure>
      <measure xml:id="measure-L61" n="71">
       <staff xml:id="staff-L61F2N1" n="1">
        <layer xml:id="layer-L61F2N1" n="1">
         <beam xml:id="beam-L62F2-L66F2">
          <note xml:id="note-L62F2" dur="8" oct="5" pname="f">
           <accid xml:id="accid-L62F2" accid="n" func="caution" />
          </note>
          <note xml:id="note-L64F2" dur="8" oct="5" pname="g" accid.ges="n" />
          <note xml:id="note-L66F2" dur="8" oct="5" pname="e" accid="n">
           <artic xml:id="artic-L66F2" artic="stacc" />
          </note>
         </beam>
         <note xml:id="note-L68F2" dur="4" oct="5" pname="d" accid.ges="n" />
         <note xml:id="note-L72F2" dur="8" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L61F1N1" n="2">
        <layer xml:id="layer-L61F1N1" n="1">
         <beam xml:id="beam-L62F1-L67F1">
          <note xml:id="note-L62F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L63F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L64F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L65F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L66F1" dur="16" oct="3" pname="a" accid.ges="n" />
          <note xml:id="note-L67F1" dur="16" oct="4" pname="c" accid="s" />
         </beam>
         <beam xml:id="beam-L68F1-L73F1">
          <note xml:id="note-L68F1" dur="16" oct="3" pname="d" accid.ges="n" />
          <note xml:id="note-L69F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L70F1" dur="16" oct="4" pname="c" accid.ges="s" />
          <note xml:id="note-L71F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L72F1" dur="16" oct="4" pname="c" accid="n" />
          <note xml:id="note-L73F1" dur="16" oct="3" pname="a" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L62F2-L64F2" staff="1" startid="#note-L62F2" endid="#note-L64F2" />
      </measure>
      <sb xml:id="sb-L75F1" type="z" />
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by Monceber**
closes #1938 
- fixed code for hairpins to take into account spanningType and adjust accordingly

image

### CODE REVIEW

File: src/hairpin.cpp [hunk 1]
```diff
@@ -167,17 +169,31 @@ std::pair<int, int> Hairpin::GetBarlineOverlapAdjustment(int doubleUnit, int lef
...
     int rightAdjustment = 0;
-    BarLine *rightBarline = endMeasure->GetRightBarLine();
+    BarLine *rightBarline = NULL;
+    if (spanningType == SPANNING_START_END || spanningType == SPANNING_END) {
+        rightBarline = endMeasure->GetRightBarLine();
+    }
+    else if (spanningType == SPANNING_START)
+    {
+        System *startSystem = vrv_cast<System *>(GetStart()->GetFirstAncestor(SYSTEM));
+        ClassIdComparison cmp(MEASURE);
```
Comment (lpugin) [inline src/hairpin.cpp:192]: I usually `assert(startSystem)` even though I agree it is extremely unlikely to fail. Do you think it is too much? If you think so we would need to find a rule when to assert it and when not. But if we cannot define such a rule I would prefer simply always to assert them

Comment (Monceber) [reply src/hairpin.cpp:192]: No, I agree that it's safer to check whether pointer is actually valid. However, I'd use a simple `if(...)` check instead of `assert(...)`, so that we do not crash right away just because of error in encoding or something among those lines.

Comment (lpugin) [reply src/hairpin.cpp:192]: Glad to hear we are on the same line! Checking with `if` is good too. But for cases such as this one I think an `assert` is enough. I am fine either way.
