### PR TITLE
Fix score condensation 

### LINKED ISSUE #2740: Condense staves also containing rests and spaces
At the moment, staves are condensed when they contain only measure rest `<mRest>` elements (see [score-010.mei](https://www.verovio.org/test-suite.xhtml?cat=score#example-score-010)), 
but it would make sense to also allow `rest`s and `space`s to constitute an empty, condensable staff.

Example: here, I would expect both solo instruments to be condensed (i.e. not shown) when called with `--condense-first-page`, but they only disappear, if the `rest`s in the upbeat are exchanged with `mRest:`s (but then the upbeat bar is far too wide): 

Bildschirmfoto 2022-03-25 um 12 41 04

<details>
<summary>Example MEI</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.1">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Optimize Score</title>
            <respStmt/>
         </titleStmt>
         <pubStmt>
            <date isodate="2022-03-25" type="encoding-date">2022-03-25</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-ydj7u6">
         <appInfo xml:id="appinfo-dzxrmq">
            <application xml:id="application-mrx7e3" isodate="2022-03-25T12:31:38" version="3.10.0-dev-4d8c60d">
               <name xml:id="name-vckcp6">Verovio</name>
               <p xml:id="p-ec05a1">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mn9kol7">
            <score xml:id="swgsof8">
               <scoreDef xml:id="s6wjhj8" optimize="true">
                  <pgHead xml:id="pumh11y">
                     <rend xml:id="rscy2ph" halign="center" valign="top">Optimize Score</rend>
                  </pgHead>
                  <staffGrp xml:id="s9nag9a">
                     <staffDef xml:id="sg172i7" n="1" lines="5" ppq="1" trans.diat="-1.000000" trans.semi="-2.000000">
                        <label xml:id="lsm895r">Klarinette in B</label>
                        <clef xml:id="clgo3nk" shape="G" line="2"/>
                        <keySig xml:id="kntlady" sig="0"/>
                        <meterSig xml:id="mwae4kd" count="3" unit="4"/>
                     </staffDef>
                     <staffDef xml:id="sif6azo" n="2" lines="5" ppq="1" trans.diat="-4.000000" trans.semi="-7.000000">
                        <label xml:id="llqvcjq">Horn in F</label>
                        <clef xml:id="c10bwyf" shape="G" line="2"/>
                        <keySig xml:id="k9l14xc" sig="1f"/>
                        <meterSig xml:id="mogkb3q" count="3" unit="4"/>
                     </staffDef>
                     <staffGrp xml:id="sit6dwq" bar.thru="true">
                        <label xml:id="le2ezfe">Klavier</label>
                        <staffDef xml:id="sjis4kp" n="3" lines="5" ppq="1">
                           <clef xml:id="ccc2hqq" shape="G" line="2"/>
                           <keySig xml:id="knes6s6" sig="2f"/>
                           <meterSig xml:id="m43ncsg" count="3" unit="4"/>
                        </staffDef>
                        <staffDef xml:id="s47row2" n="4" lines="5" ppq="1">
                           <clef xml:id="clgjpgj" shape="F" line="4"/>
                           <keySig xml:id="kfpfzef" sig="2f"/>
                           <meterSig xml:id="m4ysznu" count="3" unit="4"/>
                        </staffDef>
                        <grpSym xml:id="g4lolq8" symbol="brace"/>
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section xml:id="ssuxdkh">
                  <measure xml:id="mm5siwe" n="0" metcon="false">
                     <staff xml:id="spqywhj" n="1">
                        <layer xml:id="lw8g6e1" n="1">
                           <rest xml:id="r7ovzsj" dur="4"/>
                        </layer>
                     </staff>
                     <staff xml:id="snukqom" n="2">
                        <layer xml:id="l5vzoo3" n="1">
                           <rest xml:id="rr0mkoh" dur="4"/>
                        </layer>
                     </staff>
                     <staff xml:id="s6m66o2" n="3">
                        <layer xml:id="leevg38" n="1">
                           <note xml:id="nykwlot" dur="4" oct="4" pname="b" stem.dir="down" accid.ges="f"/>
                        </layer>
                     </staff>
                     <staff xml:id="s7ai98e" n="4">
                        <layer xml:id="ld4rm8e" n="5">
                           <rest xml:id="rsms4rh" dur="4"/>
                        </layer>
                     </staff>
                  </measure>
                  <measure xml:id="m7pm79u" right="end" n="1">
                     <staff xml:id="s8m8i8o" n="1">
                        <layer xml:id="l670r6v" n="1">
                           <mRest xml:id="mo7bhwo"/>
                        </layer>
                     </staff>
                     <staff xml:id="sk9ws5v" n="2">
                        <layer xml:id="l9vfkuw" n="1">
                           <mRest xml:id="mud9ad2"/>
                        </layer>
                     </staff>
                     <staff xml:id="sme8a1l" n="3">
                        <layer xml:id="l93kra0" n="1">
                           <note xml:id="n5ro2p2" dur="4" oct="5" pname="e" stem.dir="down" accid.ges="f"/>
                           <note xml:id="nwip53m" dur="4" oct="4" pname="b" stem.dir="down" accid.ges="f"/>
                           <note xml:id="nr3q50z" dur="4" oct="4" pname="g" stem.dir="up"/>
                        </layer>
                     </staff>
                     <staff xml:id="sjh7i5e" n="4">
                        <layer xml:id="l80949p" n="5">
                           <note xml:id="ndznzvo" dur="4" oct="2" pname="e" stem.dir="up" accid.ges="f"/>
                           <chord xml:id="cmc752z" dur="4" stem.dir="down">
                              <note xml:id="n9s34k6" oct="2" pname="b" accid.ges="f"/>
                              <note xml:id="ndkintp" oct="3" pname="g"/>
                           </chord>
                           <chord xml:id="cwbk6hb" dur="4" stem.dir="down">
                              <note xml:id="nrmj2xu" oct="2" pname="b" accid.ges="f"/>
                              <note xml:id="nnk1vaa" oct="3" pname="g"/>
                           </chord>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>

```
</details>

I guess this portion of the code relates to this request: 
https://github.com/rism-digital/verovio/blob/3749e205a6249bf28f6e6c5ef229b08194d49efa/src/staff.cpp#L493-L498

Relates to: #914, #1667, #1883.

### PR DESCRIPTION
**Pull request by rettinghaus**
This changes the check for `mRest` into a check for `note` on a staff.
fixes #2740

### CODE REVIEW

File: src/staff.cpp [hunk 1]
```diff
@@ -490,10 +490,10 @@ int Staff::ScoreDefOptimize(FunctorParams *functorParams)
     matchTypeLayer.ReverseComparison();
     this->FindAllDescendantsByComparison(&layers, &matchTypeLayer);
 
-    ListOfObjects mRests = this->FindAllDescendantsByType(MREST);
+    ListOfObjects notes = this->FindAllDescendantsByType(NOTE);
 
     // Show the staff only if no layer with content or only mRests
```
Comment (ahankinson) [inline src/staff.cpp:495]: I think this comment is now outdated.

Comment (rettinghaus) [reply src/staff.cpp]: Yes, thanks.

File: src/staff.cpp [hunk 2]
```diff
@@ -490,10 +490,10 @@ int Staff::ScoreDefOptimize(FunctorParams *functorParams)
     matchTypeLayer.ReverseComparison();
     this->FindAllDescendantsByComparison(&layers, &matchTypeLayer);
 
-    ListOfObjects mRests = this->FindAllDescendantsByType(MREST);
+    ListOfObjects notes = this->FindAllDescendantsByType(NOTE);
```
Comment (lpugin) [inline src/staff.cpp:493]: If you are using notes as a condition, why would you look for all of them? Finding one will be enough.

Comment (rettinghaus) [reply src/staff.cpp]: Right! Didn't think about that. Should be even faster.

Comment (rettinghaus) [reply src/staff.cpp]: Thanks for the hint!

**Comment by wergo** [comment]
Thanks a lot!
