### PR TITLE
Develop enclose dynamics

### LINKED ISSUE #1870: Editorial dynamics
Brackets and parentheses around dynamic symbols should be considered. At the moment those are identified as simple text strings:
dynam

When you add space to separate the dynamic symbol it shows a somewhat unexpected behaviour:
dynam_with_space

<details>
  <summary>MEI example</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Dynamics in brackets and parentheses</title>
         </titleStmt>
         <pubStmt>
            <respStmt>
               <persName role="encoder">Klaus Rettinghaus</persName>
               <corpName role="funder">Enote GmbH</corpName>
            </respStmt>
            <date isodate="2020-12-07">7 Dec 2020</date>
         </pubStmt>
         <seriesStmt>
            <title>Verovio test suite</title>
         </seriesStmt>
         <notesStmt>
            <annot>Brackets and parentheses around dynamic symbols are considered correctly.</annot>
         </notesStmt>
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application version="3.1.0" label="0">
               <name>Verovio</name>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp bar.thru="true">
                     <staffDef n="1" lines="5" clef.shape="G" clef.line="2" key.sig="2s" meter.count="4" meter.unit="4" />
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="1">
                     <staff n="1">
                        <layer n="1">
                           <note dur="4" oct="4" pname="a" />
                           <note dur="4" oct="4" pname="a" />
                           <note dur="2" oct="4" pname="a" />
                        </layer>
                     </staff>
                     <dynam staff="1" tstamp="1.000000">(ff)</dynam>
                     <dynam staff="1" tstamp="2.000000">
                        <rend fontfam="Times">[pp]</rend>
                     </dynam>
                     <dynam staff="1" tstamp="3.000000">([rf])</dynam>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

</details>

### PR DESCRIPTION
**Pull request by Monceber**
closes #1870

image

### CODE REVIEW

File: src/dynam.cpp [hunk 1]
```diff
@@ -98,6 +102,50 @@ std::wstring Dynam::GetSymbolStr() const
...
+                openElement.assign(L"(");
+                closeElement.assign(L")");
+                break;
+            }
+            default: break;
+        }
+        // If both opening/closing element are set - add them to the start and end of the dynam. Apply normal fontstyle
+        // to both, so that brackets are not inclined
+        if (!openElement.empty() && !closeElement.empty()) {
+            // Add opening bracket to the start of the dynam
```
Comment (lpugin) [inline src/dynam.cpp:127]: Why don't you create the `*open` and `*close` Rend only here? No need to delete them otherwise

File: include/vrv/object.h [hunk 2]
```diff
@@ -1113,6 +1113,11 @@ class Object : public BoundingBox {
      */
     virtual int PrepareDelayedTurns(FunctorParams *) { return FUNCTOR_CONTINUE; }
 
+    /**
+     * Functor for setting enlosure for the dynamics by adding corresponding text children to it
+     */
+    virtual int PrepareDynamEnclosure(FunctorParams *functoParams) { return FUNCTOR_CONTINUE; }
```
Comment (lpugin) [inline include/vrv/object.h:1119]: Remove the unnecessary `functoParams` name

**Comment by lpugin** [comment]
This PR triggers many weird changes in the test suite. 

See arpeg-006
image

Or accid-008
image

Maybe only because its base is outdated? Please double check. Thanks!

**Comment by Monceber** [comment]
Yes, it was quite outdated at this point, this totally flew over my head. I've rebased to the latest, should not be triggering any of those bases anymore.

**Comment by lpugin** [comment]
Sorry for being late, but what is the encoding for the example given at the top? I cannot see `@enclose` on `dynam` https://music-encoding.org/guidelines/dev/elements/dynam.html 
Am I missing something?

**Comment by rettinghaus** [comment]
Ooops, I thought it was already in there, as we discussed in #1870. 
But it is missing in music-encoding/music-encoding/pull/729 
I'll open a PR over there.
